import Link from "next/link";
import { ArrowRight } from "lucide-react";
import backtestSummary from "../../../docs/backtest/summary.json";
import { formatNumber } from "@/lib/utils/format";

// Generated by scripts/backtest/report.ts; regenerating the backtest updates
// these numbers automatically. Narrative claims live on /methodology.
const { models, totalSeries, firstSeason, lastSeason } = backtestSummary;

export function BacktestSummaryCard() {
  return (
    <div className="grid gap-4 p-4">
      <div>
        <div className="pp-number mt-3 text-3xl font-bold text-[var(--color-text-primary)]">
          Brier {formatNumber(models.playoff_pulse.brierScore, 3)}
        </div>
        <p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--color-text-muted)]">
          Beats coinflip ({formatNumber(models.coinflip.brierScore, 3)}),
          higher-seed-wins ({formatNumber(models.higher_seed.brierScore, 3)}), and
          home-team-wins ({formatNumber(models.home_team.brierScore, 3)}) on{" "}
          {totalSeries} historical series, {firstSeason}–{lastSeason}. Inputs
          corrected and results regenerated July 2026.
        </p>
      </div>

      <Link
        href="/methodology"
        className="inline-flex w-fit items-center gap-2 rounded-[var(--radius-sm-retro)] border-2 border-[var(--color-accent)] bg-[var(--color-accent)] px-4 py-2 text-xs font-bold uppercase tracking-[0.08em] text-[var(--color-accent-text)] transition hover:bg-[var(--color-accent-hover)]"
      >
        View methodology
        <ArrowRight className="h-4 w-4" aria-hidden />
      </Link>
    </div>
  );
}
