import Link from "next/link";
import { ArrowRight } from "lucide-react";
import backtestSummary from "../../../docs/backtest/summary.json";
import { formatNumber } from "@/lib/utils/format";

// Generated by scripts/backtest/report.ts; regenerating the backtest updates
// these numbers automatically. Narrative claims live on /methodology.
const { models, totalSeries, firstSeason, lastSeason } = backtestSummary;

export function BacktestSummaryCard() {
  return (
    <div className="grid gap-4 p-4">
      <div>
        <div className="pp-number mt-3 text-3xl font-bold text-[var(--color-text-primary)]">
          Brier {formatNumber(models.playoff_pulse.brierScore, 3)}
        </div>
        <p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--color-text-muted)]">
          Conclusively beats coinflip ({formatNumber(models.coinflip.brierScore, 3)}),
          higher-seed-wins ({formatNumber(models.higher_seed.brierScore, 3)}), and
          home-team-wins ({formatNumber(models.home_team.brierScore, 3)}) on{" "}
          {totalSeries} reconstructed historical series, {firstSeason}–{lastSeason}.
          Its point estimate trails SRS-only ({formatNumber(models.srs_proxy_only.brierScore, 3)})
          and leads net-rating-only ({formatNumber(models.net_rating_only.brierScore, 3)}),
          but neither difference is statistically distinguishable from zero.
          Results were expanded and regenerated in July 2026.
        </p>
      </div>

      <Link
        href="/methodology"
        className="pp-button pp-button-primary w-fit"
      >
        View methodology
        <ArrowRight className="h-4 w-4" aria-hidden />
      </Link>
    </div>
  );
}
